spring.application.name=chat-application
spring.data.mongodb.uri=mongodb+srv://Parvejk:BtechCSE2026@chatapp.hgkioor.mongodb.net/chatApp?retryWrites=true&w=majority&appName=chatApp

frontend.url=http://localhost:5173


